CREATE TABLE NUMBERS(
ID SERIAL,
Num INT);

INSERT INTO NUMBERS(Num) VALUES
(7),(2),(7),(7),(7),(6),(2),(2),
(4),(1),(1),(1),(2),(4),(6),(4);


SELECT N.Num
FROM NUMBERS N
WHERE N.Num=(SELECT NUM FROM NUMBERS
WHERE ID=N.ID+1) AND
N.Num=(SELECT NUM FROM NUMBERS
WHERE ID=N.ID+2);
